### PR TITLE
Updating upstream version to 0.12.3

### LINKED ISSUE #1: Please update for v4l2loopback v0.12.3 and Fedora 31 COPR
The last version of v4l2loopback you built in COPR was for F24, using version 0.9.1.
Please update COPR for Fedora 31 with v0.12.3 (current latest)

### PR DESCRIPTION
**Pull request by cardil**
This PR will fix #1

### CODE REVIEW

**Review by fabiand — APPROVED** [review]
lgtm

Ha - Nice to see that somebody else was having the same thought to get it updated ;)

**Comment by fabiand** [comment]
I just can't merge it ..

@danielkza any chance to get this merged?

**Comment by danielkza** [comment]
@fabiand I did not a have a chance to test the updated package yet (and might not for a while). If you can confirm that it also works for you I can merge it.

**Comment by rborer** [comment]
Hi, I'm brand new to v42loopback so I cannot confirm that it fully works (yet). But what I can confirm is that:

- I was able to build this PR under Fedora 31 :white_check_mark: 
- I was able to load the module into my kernel (version `5.5.17-200.fc31.x86_64`) :white_check_mark:

**Pull request merged**
